version: '3.8'
services:
  cat-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: catdb
    networks:
      - 2annalyse
  
networks:
  2annalyse: